# Generated by Django 6.0.3 on 2026-03-19 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='เลขออร์เดอร์')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง')),
                ('print_date', models.DateField(blank=True, null=True, verbose_name='วันที่พิมพ์เสื้อ')),
                ('source', models.CharField(choices=[('เพจเสื้อเนินสูง', 'เพจเสื้อเนินสูง'), ('เพจเสื้อคนงาน', 'เพจเสื้อคนงาน'), ('เฮีย&เจ๊', 'เฮีย&เจ๊'), ('หน้าร้าน', 'หน้าร้าน'), ('เพจปักผ้า', 'เพจปักผ้า'), ('LINE OA', 'LINE OA'), ('เพจร้าน Yada', 'เพจร้าน Yada'), ('เพจเสื้อทุเรียน', 'เพจเสื้อทุเรียน')], max_length=50, verbose_name='แหล่งที่มา')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ชื่อลูกค้า')),
                ('customer_link', models.CharField(blank=True, max_length=500, verbose_name='Facebook/เบอร์โทร')),
                ('shirt_name', models.CharField(max_length=200, verbose_name='ชื่องาน/ชื่อเสื้อ')),
                ('fabric_spec', models.TextField(blank=True, help_text='แสดงเฉพาะ source=เพจเสื้อคนงาน', verbose_name='spec ผ้า')),
                ('special_note', models.TextField(blank=True, verbose_name='คำสั่งพิเศษ')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดรวม')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='มัดจำ')),
                ('delivery_method', models.CharField(choices=[('รับเอง', 'รับเอง'), ('ส่ง', 'ส่ง')], default='รับเอง', max_length=20, verbose_name='วิธีรับสินค้า')),
                ('status', models.CharField(choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('กำลังผลิต', 'กำลังผลิต'), ('เสร็จแล้ว', 'เสร็จแล้ว'), ('ส่งแล้ว', 'ส่งแล้ว')], default='รอดำเนินการ', max_length=20, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'ออร์เดอร์',
                'verbose_name_plural': 'ออร์เดอร์',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_image', models.ImageField(blank=True, upload_to='designs/', verbose_name='รูปดีไซน์')),
                ('shirt_type', models.CharField(choices=[('แขนสั้น', 'แขนสั้น'), ('แขนยาว', 'แขนยาว'), ('โปโล', 'โปโล'), ('อื่นๆ', 'อื่นๆ')], default='แขนสั้น', max_length=20, verbose_name='ประเภทเสื้อ')),
                ('color', models.CharField(max_length=50, verbose_name='สีเสื้อ')),
                ('qty_xs', models.IntegerField(default=0, verbose_name='XS')),
                ('qty_ss', models.IntegerField(default=0, verbose_name='SS')),
                ('qty_s', models.IntegerField(default=0, verbose_name='S')),
                ('qty_m', models.IntegerField(default=0, verbose_name='M')),
                ('qty_l', models.IntegerField(default=0, verbose_name='L')),
                ('qty_xl', models.IntegerField(default=0, verbose_name='XL')),
                ('qty_2xl', models.IntegerField(default=0, verbose_name='2XL')),
                ('qty_3xl', models.IntegerField(default=0, verbose_name='3XL')),
                ('qty_4xl', models.IntegerField(default=0, verbose_name='4XL')),
                ('qty_5xl', models.IntegerField(default=0, verbose_name='5XL')),
                ('qty_6xl', models.IntegerField(default=0, verbose_name='6XL')),
                ('qty_custom_label', models.CharField(blank=True, max_length=50, verbose_name='ไซส์พิเศษ (label)')),
                ('qty_custom', models.IntegerField(default=0, verbose_name='จำนวนไซส์พิเศษ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'รายการเสื้อ',
                'verbose_name_plural': 'รายการเสื้อ',
            },
        ),
    ]
