# Generated by Django 6.0.3 on 2026-03-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_2xl',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_3xl',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_4xl',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_5xl',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_6xl',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_custom',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_custom_label',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_l',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_m',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_s',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_ss',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_xl',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qty_xs',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sizes',
            field=models.JSONField(blank=True, default=list, help_text='[{"label": "S", "qty": 5}, {"label": "M", "qty": 10}, ...]', verbose_name='ไซส์และจำนวน'),
        ),
    ]
