# Generated by Django 6.0.3 on 2026-03-20 04:27

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_qty_2xl_remove_orderitem_qty_3xl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='design_image',
            field=models.ImageField(blank=True, upload_to=orders.models.design_upload_path, verbose_name='รูปดีไซน์'),
        ),
    ]
