# Generated by Django 6.0.3 on 2026-03-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_design_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shirt_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='collar_type',
            field=models.CharField(choices=[('คอกลม', 'คอกลม'), ('คอวี', 'คอวี'), ('โปโล', 'โปโล'), ('คอปกวี', 'คอปกวี'), ('คอกีฬา', 'คอกีฬา'), ('อื่นๆ', 'อื่นๆ')], default='คอกลม', max_length=20, verbose_name='ประเภทคอ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sleeve_type',
            field=models.CharField(choices=[('แขนสั้น', 'แขนสั้น'), ('แขนยาว', 'แขนยาว'), ('แขนกุด', 'แขนกุด')], default='แขนสั้น', max_length=20, verbose_name='ประเภทแขน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('เพจเสื้อเนินสูง', 'เพจเสื้อเนินสูง'), ('เพจเสื้อคนงาน', 'เพจเสื้อคนงาน'), ('เฮีย&เจ๊', 'เฮีย&เจ๊'), ('หน้าร้าน', 'หน้าร้าน'), ('เพจปักผ้า', 'เพจปักผ้า'), ('LINE OA', 'LINE OA'), ('เพจร้าน Yada', 'เพจร้าน Yada'), ('เพจเสื้อทุเรียน', 'เพจเสื้อทุเรียน'), ('Shopee', 'Shopee'), ('Tiktok', 'Tiktok')], max_length=50, verbose_name='แหล่งที่มา'),
        ),
    ]
