# Generated by Django 6.0.3 on 2026-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_shirt_type_orderitem_collar_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='ที่อยู่จัดส่ง'),
        ),
    ]
