# Generated by Django 5.1.15 on 2026-05-05 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทร')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'คนเย็บ',
                'verbose_name_plural': 'คนเย็บ',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='awaiting_pickup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='รอมารับเมื่อ'),
        ),
        migrations.AddField(
            model_name='order',
            name='cut_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ตัดเสร็จเมื่อ'),
        ),
        migrations.AddField(
            model_name='order',
            name='needs_repair',
            field=models.BooleanField(default=False, verbose_name='ต้องซ่อม'),
        ),
        migrations.AddField(
            model_name='order',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='รีดแพ็คเสร็จเมื่อ'),
        ),
        migrations.AddField(
            model_name='order',
            name='print_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='พิมพ์เสร็จเมื่อ'),
        ),
        migrations.AddField(
            model_name='order',
            name='repair_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ซ่อมเสร็จล่าสุดเมื่อ'),
        ),
        migrations.AddField(
            model_name='order',
            name='roll_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='โรลเสร็จเมื่อ'),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_to_tailors_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ส่งเย็บเมื่อ'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ส่งของเมื่อ'),
        ),
        migrations.AddField(
            model_name='order',
            name='sort_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='คัดเสร็จเมื่อ'),
        ),
        migrations.CreateModel(
            name='StageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20, verbose_name='แผนก')),
                ('action', models.CharField(max_length=30, verbose_name='การกระทำ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'log สถานะ',
                'verbose_name_plural': 'log สถานะ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='tailors',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.tailor', verbose_name='คนเย็บ'),
        ),
    ]
