# Generated by Django 6.0.3 on 2026-05-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_tailor_order_awaiting_pickup_at_order_cut_done_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order_index', 'id'], 'verbose_name': 'รายการเสื้อ', 'verbose_name_plural': 'รายการเสื้อ'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='collar_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sleeve_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='ลำดับ'),
        ),
        migrations.CreateModel(
            name='ShirtVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collar', models.CharField(blank=True, help_text='เช่น คอกลม, คอวี, คอเรือ', max_length=50, verbose_name='คอ')),
                ('sleeve', models.CharField(blank=True, help_text='เช่น แขนสั้น, แขนยาว, แขนกุด', max_length=50, verbose_name='แขน')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='สี')),
                ('sizes', models.JSONField(default=list, help_text='[{"label":"S","qty":5}, ...]', verbose_name='ไซส์และจำนวน')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='โน้ตเฉพาะแบบนี้')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='orders.orderitem', verbose_name='รายการเสื้อ')),
            ],
            options={
                'verbose_name': 'แบบ',
                'verbose_name_plural': 'แบบ',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
