# Generated by Django 6.0.3 on 2026-05-13 23:03

from django.db import migrations, models


def seed_default_pin(apps, schema_editor):
    PIN = apps.get_model('orders', 'DepartmentPIN')
    PIN.objects.get_or_create(defaults={'pin': '1234'})


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_options_remove_orderitem_collar_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=4, verbose_name='PIN 4 หลัก')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PIN แผนก',
                'verbose_name_plural': 'PIN แผนก',
            },
        ),
        migrations.RunPython(seed_default_pin, migrations.RunPython.noop),
    ]
