# Generated by Django 6.0.3 on 2026-05-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_departmentpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='ด่วน!'),
        ),
    ]
