# Generated by Django 6.0.3 on 2026-05-20 09:49

from datetime import datetime, time

from django.db import migrations, models
from django.utils import timezone


def backfill_printed_at(apps, schema_editor):
    """Legacy orders (existing at migrate time) count as already printed:
    set printed_at = created_date so they don't show "ยังไม่พิมพ์ใบงาน".
    Orders created after deploy keep printed_at = NULL = not printed yet.
    """
    Order = apps.get_model('orders', 'Order')
    for o in Order.objects.filter(printed_at__isnull=True):
        if not o.created_date:
            continue
        dt = datetime.combine(o.created_date, time(0, 0))
        if timezone.is_naive(dt):
            dt = timezone.make_aware(dt)
        o.printed_at = dt
        o.save(update_fields=['printed_at'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_created_at_order_created_by_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='พิมพ์ใบงานเมื่อ'),
        ),
        migrations.RunPython(backfill_printed_at, noop),
    ]
