# Generated by Django 6.0.3 on 2026-05-23 07:25

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_production_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=orders.models.master_upload_path, verbose_name='รูปมาสเตอร์')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_images', to='orders.order')),
            ],
            options={
                'verbose_name': 'รูปมาสเตอร์',
                'verbose_name_plural': 'รูปมาสเตอร์',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
