# Generated by Django 6.0.3 on 2026-05-23 09:38

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_masterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signed_image',
            field=models.ImageField(blank=True, null=True, upload_to=orders.models.signed_upload_path, verbose_name='รูปที่เซ็นแล้ว'),
        ),
    ]
