# Generated by Django 6.0.3 on 2026-05-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_signed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='production_place',
            field=models.CharField(choices=[('ผลิตเอง', 'ผลิตเอง'), ('ร้านแอม', 'ร้านแอม'), ('ร้านแบ้งค์', 'ร้านแบ้งค์'), ('ร้านตูน', 'ร้านตูน')], default='ผลิตเอง', max_length=20, verbose_name='ผลิตที่'),
        ),
    ]
