# Generated by Django 5.2.14 on 2026-06-21 00:26

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_production_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_note',
            field=models.TextField(blank=True, verbose_name='โน้ตเพิ่มเติม'),
        ),
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=orders.models.extra_upload_path, verbose_name='รูปเพิ่มเติม')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='orders.order')),
            ],
            options={
                'verbose_name': 'รูปเพิ่มเติม',
                'verbose_name_plural': 'รูปเพิ่มเติม',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExtraNameRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='ไซส์')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='เบอร์')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='ชื่อ')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_name_rows', to='orders.order')),
            ],
            options={
                'verbose_name': 'แถวรันชื่อ',
                'verbose_name_plural': 'แถวรันชื่อ',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
