# Generated by Django 5.2.14 on 2026-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_extra_note_extraimage_extranamerow'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_doc_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='เลขใบงานออกแบบ'),
        ),
        migrations.AddField(
            model_name='order',
            name='designer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='คนออกแบบ'),
        ),
    ]
