# Generated by Django 5.2.14 on 2026-07-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_design_doc_number_order_designer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiting_confirm',
            field=models.BooleanField(default=False, verbose_name='รอคอนเฟิร์ม'),
        ),
    ]
