# Generated by Django 5.2.14 on 2026-07-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_waiting_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อลูกค้า')),
                ('facebook_link', models.CharField(blank=True, max_length=500, verbose_name='Facebook/ลิงก์')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='เบอร์โทร')),
                ('note', models.TextField(blank=True, verbose_name='โน้ต')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.customer', verbose_name='โปรไฟล์ลูกค้า'),
        ),
        migrations.CreateModel(
            name='CustomerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='รายการ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา/ตัว')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.customer')),
            ],
            options={
                'verbose_name': 'ราคาลูกค้า',
                'verbose_name_plural': 'ราคาลูกค้า',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
