# Generated by Django 5.2.14 on 2026-07-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_customer_order_customer_customerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orders', to='orders.order', verbose_name='ใบเพิ่มจากใบ'),
        ),
    ]
