# Generated by Django 5.2.14 on 2026-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_parent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='brief_job_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brief job id'),
        ),
    ]
