# Generated by Django 5.2.14 on 2026-07-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_brief_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อกลุ่ม')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name': 'กลุ่มลูกค้า',
                'verbose_name_plural': 'กลุ่มลูกค้า',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customers', to='orders.customertag', verbose_name='กลุ่ม'),
        ),
    ]
