# Generated by Django 5.2.14 on 2026-07-26 23:31

from django.db import migrations, models


# seed ต้นทุนเริ่มต้น (แก้ทีหลังผ่าน Django admin) — ทำใน migration เลย
# เพื่อให้รายงานกำไรใช้งานได้ทันทีหลัง migrate (Lessons ข้อ 3)
SEED_COSTS = [('short', 50), ('long', 65), ('polo', 85)]


def seed_shirt_costs(apps, schema_editor):
    ShirtCost = apps.get_model('orders', 'ShirtCost')
    for shirt_type, cost in SEED_COSTS:
        ShirtCost.objects.get_or_create(shirt_type=shirt_type, defaults={'cost': cost})


def unseed_shirt_costs(apps, schema_editor):
    ShirtCost = apps.get_model('orders', 'ShirtCost')
    ShirtCost.objects.filter(shirt_type__in=[t for t, _ in SEED_COSTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_userpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_type', models.CharField(choices=[('short', 'แขนสั้น'), ('long', 'แขนยาว'), ('polo', 'โปโล')], max_length=10, unique=True, verbose_name='ประเภทเสื้อ')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ต้นทุน/ตัว (บาท)')),
            ],
            options={
                'verbose_name': 'ต้นทุนเสื้อ',
                'verbose_name_plural': 'ต้นทุนเสื้อ',
                'ordering': ['shirt_type'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shirt_type',
            field=models.CharField(blank=True, choices=[('short', 'แขนสั้น'), ('long', 'แขนยาว'), ('polo', 'โปโล')], default='', max_length=10, verbose_name='ประเภทเสื้อ (ต้นทุน)'),
        ),
        migrations.CreateModel(
            name='DailyAdSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('page', models.CharField(choices=[('เพจเสื้อเนินสูง', 'เพจเสื้อเนินสูง'), ('เพจเสื้อคนงาน', 'เพจเสื้อคนงาน'), ('เฮีย&เจ๊', 'เฮีย&เจ๊'), ('หน้าร้าน', 'หน้าร้าน'), ('เพจปักผ้า', 'เพจปักผ้า'), ('LINE OA', 'LINE OA'), ('เพจร้าน Yada', 'เพจร้าน Yada'), ('เพจเสื้อทุเรียน', 'เพจเสื้อทุเรียน'), ('Shopee', 'Shopee'), ('Tiktok', 'Tiktok')], max_length=50, verbose_name='เพจ/แหล่งที่มา')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าแอด (บาท)')),
            ],
            options={
                'verbose_name': 'ค่าแอดรายวัน',
                'verbose_name_plural': 'ค่าแอดรายวัน',
                'ordering': ['-date', 'page'],
                'constraints': [models.UniqueConstraint(fields=('date', 'page'), name='uniq_adspend_date_page')],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('page', models.CharField(max_length=50, verbose_name='เพจ/แหล่งที่มา')),
                ('orders', models.PositiveIntegerField(default=0, verbose_name='จำนวนใบ')),
                ('shirts', models.PositiveIntegerField(default=0, verbose_name='จำนวนตัว')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดขาย')),
                ('shirt_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ต้นทุนเสื้อ')),
                ('ad_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าแอด')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='กำไรขั้นต้น')),
                ('net_after_ads', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='กำไรหลังหักแอด')),
                ('defaulted_shirts', models.PositiveIntegerField(default=0, verbose_name='ตัวที่ใช้ต้นทุน default')),
            ],
            options={
                'verbose_name': 'สรุปกำไรรายวัน (cache)',
                'verbose_name_plural': 'สรุปกำไรรายวัน (cache)',
                'ordering': ['-date', 'page'],
                'constraints': [models.UniqueConstraint(fields=('date', 'page'), name='uniq_summary_date_page')],
            },
        ),
        migrations.RunPython(seed_shirt_costs, unseed_shirt_costs),
    ]
