# Generated by Django 6.0.3 on 2026-07-31 02:20

from django.db import migrations, models


def backfill_order_index(apps, schema_editor):
    # ให้คนเย็บเดิมได้ลำดับตามชื่อ (ลำดับที่เห็นอยู่ก่อนหน้า) — คนใหม่หลังจากนี้ default 0 ลอยขึ้นบนรอจัด
    Tailor = apps.get_model('orders', 'Tailor')
    for position, tailor in enumerate(Tailor.objects.order_by('name'), start=1):
        Tailor.objects.filter(pk=tailor.pk).update(order_index=position)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_profit_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tailor',
            options={'ordering': ['order_index', 'name'], 'verbose_name': 'คนเย็บ', 'verbose_name_plural': 'คนเย็บ'},
        ),
        migrations.AddField(
            model_name='tailor',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='ลำดับ'),
        ),
        migrations.RunPython(backfill_order_index, migrations.RunPython.noop),
    ]
