# Generated by Django 6.0.3 on 2026-08-15 00:00
# เพิ่มเพจใหม่ 2 เพจใน SOURCE_CHOICES: เพจเสื้อช่างPK, เพจเจ๊ปิ๋วเสื้อซิ่ง
# choices เปลี่ยนอย่างเดียว — ไม่แตะข้อมูลเดิม (Postgres ไม่มี constraint จาก choices)

from django.db import migrations, models


SOURCE_CHOICES = [
    ('เพจเสื้อเนินสูง', 'เพจเสื้อเนินสูง'),
    ('เพจเสื้อคนงาน', 'เพจเสื้อคนงาน'),
    ('เฮีย&เจ๊', 'เฮีย&เจ๊'),
    ('หน้าร้าน', 'หน้าร้าน'),
    ('เพจปักผ้า', 'เพจปักผ้า'),
    ('LINE OA', 'LINE OA'),
    ('เพจร้าน Yada', 'เพจร้าน Yada'),
    ('เพจเสื้อทุเรียน', 'เพจเสื้อทุเรียน'),
    ('เพจเสื้อช่างPK', 'เพจเสื้อช่างPK'),
    ('เพจเจ๊ปิ๋วเสื้อซิ่ง', 'เพจเจ๊ปิ๋วเสื้อซิ่ง'),
    ('Shopee', 'Shopee'),
    ('Tiktok', 'Tiktok'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_tailor_order_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyadspend',
            name='page',
            field=models.CharField(choices=SOURCE_CHOICES, max_length=50, verbose_name='เพจ/แหล่งที่มา'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=SOURCE_CHOICES, max_length=50, verbose_name='แหล่งที่มา'),
        ),
    ]
