# Generated by Django 5.2.14 on 2026-08-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_split_shopee_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirtvariant',
            name='pocket',
            field=models.BooleanField(default=False, verbose_name='กระเป๋าหน้าอก'),
        ),
    ]
