# Generated by Django 6.0.3 on 2026-08-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_shirtvariant_pocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_mockup',
            field=models.BooleanField(default=False, verbose_name='จากโปรแกรม Mockup'),
        ),
    ]
