# Generated by Django 6.0.3 on 2026-08-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_from_mockup'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='design_doc_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='เลขใบงานออกแบบ (เฉพาะรายการนี้)'),
        ),
    ]
